--
-- Database: 'cse 340 project', public schema
-- Assignment 2, Task 2
--


-- Drop existing enum type
DROP TYPE IF EXISTS public.account_type;

-- Create account_type enum
CREATE TYPE public.account_type AS ENUM(
  'Client',
  'Employee',
  'Admin'
);

-- Drop existing tables if they exist
DROP TABLE IF EXISTS inventory, classification, account;

-- Create classification table
CREATE TABLE public.classification (
  classification_id INT GENERATED BY DEFAULT AS IDENTITY,
  classification_name CHARACTER VARYING NOT NULL,
  CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

-- Create inventory table
CREATE TABLE IF NOT EXISTS public.inventory (
  inv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  inv_make character varying NOT NULL,
  inv_model character varying NOT NULL,
  inv_year character(4) NOT NULL,
  inv_description text NOT NULL,
  inv_image character varying NOT NULL,
  inv_thumbnail character varying NOT NULL,
  inv_price numeric(9, 0) NOT NULL,
  inv_miles integer NOT NULL,
  inv_color character varying NOT NULL,
  classification_id integer NOT NULL,
  CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)
);

-- Create relationship between classification and inventory tables
ALTER TABLE IF EXISTS public.inventory
  ADD CONSTRAINT fk_classification FOREIGN KEY (classification_id)
  REFERENCES public.classification (classification_id) MATCH SIMPLE
  ON UPDATE CASCADE
  ON DELETE NO ACTION;

-- Create account table
CREATE TABLE IF NOT EXISTS public.account (
  account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  account_firstname character varying NOT NULL,
  account_lastname character varying NOT NULL,
  account_email character varying NOT NULL,
  account_password character varying NOT NULL,
  account_type account_type NOT NULL DEFAULT 'Client'::account_type,
  CONSTRAINT account_pkey PRIMARY KEY (account_id)
);

-- Insert data into classification
INSERT INTO classification (classification_name) VALUES ('Sport'), ('SUV'), ('Truck');

-- Insert data into inventory
INSERT INTO inventory (
  inv_make, inv_model, inv_year, inv_description, inv_image,
  inv_thumbnail, inv_price, inv_miles, inv_color, classification_id
) VALUES
  ('GM', 'Hummer', '2022', 'A car with small interiors', '/images/hummer.jpg', '/images/thumbs/hummer.jpg', 60000, 5000, 'Black', 1),
  ('Toyota', 'Supra', '2023', 'A fast sports car', '/images/supra.jpg', '/images/thumbs/supra.jpg', 50000, 3000, 'Red', 1);

-- TASK 1 QUERY 4: Update description for Hummer
UPDATE inventory
SET inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior')
WHERE inv_make = 'GM' AND inv_model = 'Hummer';

-- TASK 1 QUERY 6: Update image and thumbnail paths
UPDATE inventory
SET inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
    inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/');
